#!/usr/bin/env bash
# NixOS adaptation of esteid-update-nssdb from https://github.com/open-eid
nix-env -i opensc nss qdigidoc
LIB=`nix-env --query opensc --no-name --out-path`/lib/onepin-opensc-pkcs11.so
NSSPATH=$(nix-store --query `nix-instantiate '<nixpkgs>' -A nss` | grep tools)
NSSDB=$HOME/.pki/nssdb
CERTUTIL="$NSSPATH/bin/certutil -d sql:$NSSDB"
MODUTIL="$NSSPATH/bin/modutil -force -dbdir sql:$NSSDB"
DIGIDOC=$(nix-store --query `nix-instantiate '<nixpkgs>' -A libdigidoc`)/share/libdigidoc
CERTS="$DIGIDOC"

if [ ! -f $NSSDB/cert9.db ]; then
    echo "Initializing new database"
    mkdir -p $NSSDB
    $CERTUTIL -N --empty-password
fi

for DIR in $CERTS; do
    for YEAR in 2011 2015; do
        CERT="$DIR/ESTEID-SK $YEAR.crt"
        if [ -e "$CERT" ]; then
            if grep -q ESTEID-SK_$YEAR $NSSDB/cert9.db; then
                echo "$CERT already imported"
            else
                echo "Importing $CERT"
                PCSCLITE_CSOCK_NAME=/dev/null $CERTUTIL -A -t ",," -n "ESTEID-SK_$YEAR" -i "$CERT"
            fi
        else
            echo "$CERT missing, perhaps Estonian ID-card stack needs updating?"
        fi
    done
done

echo "Enabling ID-card functionality in Google Chrome/Chromium via $LIB"
$MODUTIL -delete opensc-pkcs11
$MODUTIL -add opensc-pkcs11 -libfile $LIB -mechanisms FRIENDLY
