#!/usr/bin/env bash

# Restore cursor and move to new line when terminated
trap 'tput cnorm; echo' EXIT
trap 'exit 127' HUP INT TERM

# Make text cursor invisible
tput civis
# Save cursor position
tput sc

COUNT=0

VAL=
for x in $(grep -Eo '[[:alpha:]]+|[0-9]+' <<<"$1"); do
    if [ "$VAL" == "" ]; then
        VAL=$x
    else
        if [ "$x" == "h" ]; then
            COUNT=$(($COUNT + $VAL * 60 * 60))
        fi
        if [ "$x" == "m" ]; then
            COUNT=$(($COUNT + $VAL * 60))
        fi
        if [ "$x" == "s" ]; then
            COUNT=$(($COUNT + $VAL))
        fi
        VAL=
    fi
done

while [ $COUNT -ge 0 ]; do
    tput rc
    printf "%sm%ss " "$(($COUNT / 60))" "$((COUNT % 60))"
    sleep 1s
    COUNT=$(($COUNT - 1))
done
ogg123 ~/Pollux.ogg &>/dev/null
